# Generated by Django 2.2.1 on 2019-11-22 21:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mentors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_creation', models.DateTimeField()),
                ('displayPref', models.IntegerField(default=1)),
                ('emailInvite', models.BooleanField(default=False)),
                ('emailDelete', models.BooleanField(default=False)),
                ('emailStart', models.BooleanField(default=False)),
                ('emailStop', models.BooleanField(default=False)),
                ('showHint', models.BooleanField(default=True)),
                ('mturk', models.IntegerField(default=0)),
                ('age', models.IntegerField(default=0)),
                ('code', models.CharField(blank=True, max_length=100, null=True)),
                ('comments', models.CharField(blank=True, max_length=1000, null=True)),
                ('sequence', models.TextField(default='')),
                ('cur_poll', models.IntegerField(default=1)),
                ('finished', models.BooleanField(default=False)),
                ('numq', models.IntegerField(default=0)),
                ('exp_data', models.TextField(default='{}')),
                ('mentor_applied', models.BooleanField(default=False)),
                ('mentor_profile', models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='mentors.Mentor')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
