# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-20 20:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appauth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='displayPref',
            field=models.IntegerField(default=1),
        ),
    ]
