# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-02 21:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appauth', '0002_userprofile_displaypref'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='emailDelete',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='emailInvite',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='emailStart',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='emailStop',
            field=models.BooleanField(default=True),
        ),
    ]
