# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-09 00:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appauth', '0003_auto_20160702_1713'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='showHint',
            field=models.BooleanField(default=True),
        ),
    ]
