# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-06 21:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appauth', '0004_userprofile_showhint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='emailDelete',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='emailInvite',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='emailStart',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='emailStop',
            field=models.BooleanField(default=False),
        ),
    ]
