# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-23 22:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appauth', '0006_auto_20171117_1007'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='code',
            field=models.IntegerField(default=0),
        ),
    ]
