# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-01 03:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appauth', '0007_userprofile_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='comments',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
