# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-04 19:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appauth', '0008_userprofile_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
