# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-16 18:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appauth', '0009_auto_20171204_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='cur_poll',
            field=models.IntegerField(default=369),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='sequence',
            field=models.TextField(default=''),
        ),
    ]
