# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-25 04:53
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('appauth', '0010_auto_20171216_1342'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='time_creation',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 25, 4, 52, 59, 194669, tzinfo=utc), verbose_name='time_created'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='cur_poll',
            field=models.IntegerField(default=1),
        ),
    ]
