# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-30 19:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appauth', '0014_auto_20171229_1135'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='finished',
            field=models.BooleanField(default=False),
        ),
    ]
