# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-06 16:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appauth', '0015_userprofile_finished'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='numq',
            field=models.IntegerField(default=0),
        ),
    ]
