# Generated by Django 2.2 on 2019-11-25 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mentors', '0001_initial'),
        ('appauth', '0017_userprofile_exp_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='mentor_applied',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='mentor_profile',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mentors.Mentor'),
        ),
    ]
