# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-09 15:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='open',
            field=models.IntegerField(default=0),
        ),
    ]
