# Generated by Django 2.2.1 on 2019-11-02 17:13

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import mentors.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=4)),
                ('number', models.CharField(default='1000', max_length=4)),
                ('name', models.CharField(default='none', max_length=50)),
                ('instructor', models.CharField(default='none', max_length=50)),
                ('feature_cumlative_GPA', models.IntegerField(default=0)),
                ('feature_has_taken', models.IntegerField(default=0)),
                ('feature_course_GPA', models.IntegerField(default=0)),
                ('feature_mentor_exp', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('applied', models.BooleanField(default=False)),
                ('step', models.IntegerField(default=1)),
                ('RIN', models.CharField(max_length=9, primary_key=True, serialize=False, validators=[django.core.validators.MinLengthValidator(9)])),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('GPA', mentors.models.MinMaxFloat()),
                ('email', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
                ('recommender', models.CharField(max_length=50)),
                ('compensation', models.CharField(choices=[('1', 'Pay'), ('2', 'Credit'), ('3', 'No Preference')], default='1', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('department', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_grade', models.CharField(choices=[('a', 'A'), ('a-', 'A-'), ('b+', 'B+'), ('b', 'B'), ('b-', 'B-'), ('c+', 'C+'), ('c', 'C'), ('c-', 'C-'), ('d+', 'D+'), ('d', 'D'), ('f', 'F'), ('p', 'Progressing'), ('n', 'Not Taken')], default='n', max_length=1)),
                ('have_taken', models.BooleanField(default=False)),
                ('mentor_exp', models.BooleanField(default=False)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mentors.Course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mentors.Mentor')),
            ],
        ),
    ]
