# Generated by Django 2.2.1 on 2019-11-24 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='time_slots',
            field=models.CharField(default='[]', max_length=500),
        ),
    ]
