# Generated by Django 2.2.1 on 2019-11-14 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mentors', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mentor',
            old_name='mentor_course',
            new_name='mentored_course',
        ),
    ]
