# Generated by Django 2.2.1 on 2019-11-09 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mentors', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mentor',
            name='step',
        ),
    ]
