# Generated by Django 2.2.1 on 2019-11-14 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentors', '0002_auto_20191113_2042'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='mentor_cap',
            field=models.IntegerField(default=0),
        ),
    ]
