# Generated by Django 2.2.1 on 2019-10-20 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mentors', '0002_auto_20191019_1631'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mentor',
            old_name='phone_number',
            new_name='phone',
        ),
    ]
