# Generated by Django 2.2.1 on 2019-11-24 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentors', '0002_course_time_slots'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentor',
            name='mentored_non_cs_bf',
            field=models.BooleanField(default=False),
        ),
    ]
