# Generated by Django 2.2.1 on 2019-10-20 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentors', '0003_auto_20191019_1920'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentor',
            name='recommender',
            field=models.CharField(default='', max_length=50),
        ),
    ]
