# Generated by Django 2.2.1 on 2019-11-16 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentors', '0003_course_mentor_cap'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentor',
            name='course_pref',
            field=models.CharField(max_length=10000),
        ),
    ]
