# Generated by Django 2.2.1 on 2019-11-21 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentors', '0004_auto_20191116_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentor',
            name='time_slots',
            field=models.CharField(choices=[('M_4:00-4:50PM', 'M 4:00-4:50PM'), ('M_4:00-5:50PM', 'M 4:00-5:50PM'), ('M_5:00-5:50PM', 'M 5:00-5:50PM'), ('M_6:00-6:50PM', 'M 6:00-6:50PM'), ('T_10:00-11:50AM', 'T 10:00-11:50AM'), ('T_12:00-1:50PM', 'T 12:00-1:50PM'), ('T_2:00-3:50PM', 'T 2:00-3:50PM'), ('T_4:00-4:50PM', 'T 4:00-4:50PM'), ('T_5:00-5:50AM', 'T 5:00-5:50AM'), ('T_6:00-6:50PM', 'T 6:00-6:50PM'), ('W_10:00-11:50AM', 'W 10:00-11:50AM'), ('W_12:00-1:50PM', 'W 12:00-1:50PM'), ('W_2:00-3:50PM', 'W 2:00-3:50PM'), ('W_4:00-4:50PM', 'W 4:00-4:50PM'), ('W_5:00-5:50AM', 'W 5:00-5:50AM'), ('W_6:00-6:50PM', '     W 6:00-7:50PM'), ('T_4:00-5:50AM', 'T 4:00-5:50AM'), ('T_6:00-6:50PM', 'T 6:00-7:50PM')], default=None, max_length=18),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='compensation',
            field=models.CharField(choices=[('1', 'Pay ($14/hour) '), ('2', 'Credit'), ('3', 'No Preference')], default='1', max_length=1),
        ),
    ]
