# Generated by Django 2.2.1 on 2019-10-20 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentors', '0004_mentor_recommender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentor',
            name='recommender',
            field=models.CharField(max_length=50),
        ),
    ]
