# Generated by Django 2.2.1 on 2019-11-21 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentors', '0006_auto_20191120_2236'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentor',
            name='other_times',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='mentor',
            name='relevant_info',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='time_slots',
            field=models.CharField(default='[]', max_length=1000),
        ),
    ]
