# Generated by Django 2.2.1 on 2019-11-21 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentors', '0007_auto_20191121_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentor',
            name='employed_paid_before',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mentor',
            name='studnet_status',
            field=models.CharField(choices=[('1', 'International'), ('2', 'Domestic')], default='1', max_length=1),
        ),
    ]
