# Generated by Django 2.2.1 on 2019-11-21 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentors', '0008_auto_20191121_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentor',
            name='compensation',
            field=models.CharField(choices=[('pay', 'Pay ($14/hour) '), ('credit', 'Credit'), ('no_pref', 'No Preference')], default='no_pref', max_length=1),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='studnet_status',
            field=models.CharField(choices=[('international', 'International'), ('domestic', 'Domestic')], default='international', max_length=1),
        ),
    ]
