# Generated by Django 2.2.1 on 2019-11-21 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentors', '0009_auto_20191121_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentor',
            name='compensation',
            field=models.CharField(choices=[('p', 'Pay ($14/hour) '), ('c', 'Credit'), ('n', 'No Preference')], default='no_pref', max_length=1),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='studnet_status',
            field=models.CharField(choices=[('i', 'International'), ('d', 'Domestic')], default='international', max_length=1),
        ),
    ]
