# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-02 08:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20160501_1622'),
    ]

    operations = [
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(verbose_name='response timestamp')),
            ],
        ),
        migrations.RemoveField(
            model_name='choice',
            name='item',
        ),
        migrations.RemoveField(
            model_name='item',
            name='rank',
        ),
        migrations.RemoveField(
            model_name='student',
            name='preference_dict',
        ),
        migrations.AlterField(
            model_name='keyvaluepair',
            name='key',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='polls.Item'),
        ),
        migrations.AlterField(
            model_name='keyvaluepair',
            name='value',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.AddField(
            model_name='response',
            name='allocation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Item'),
        ),
        migrations.AddField(
            model_name='response',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Question'),
        ),
        migrations.AddField(
            model_name='response',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Student'),
        ),
        migrations.AddField(
            model_name='dictionary',
            name='response',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='polls.Response'),
        ),
    ]
