# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-02 15:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20160502_0301'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dictionary',
            name='response',
        ),
        migrations.AddField(
            model_name='response',
            name='preferences',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='polls.Dictionary'),
        ),
        migrations.AlterField(
            model_name='keyvaluepair',
            name='value',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='response',
            name='allocation',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='polls.Item'),
        ),
    ]
