# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-02 15:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_auto_20160502_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='preferences',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Dictionary'),
        ),
    ]
