# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-02 16:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_auto_20160502_1148'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='response',
            name='preferences',
        ),
        migrations.AddField(
            model_name='dictionary',
            name='response',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='polls.Response'),
        ),
    ]
