# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-02 16:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_auto_20160502_1207'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='response',
            options={'ordering': ['timestamp']},
        ),
    ]
