# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-02 17:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_auto_20160502_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='allocation',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.Item'),
        ),
    ]
