# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-03 19:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_auto_20160502_1316'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='follow_up',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.Question'),
        ),
    ]
