# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-03 19:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0012_question_question_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_voters',
            field=models.ManyToManyField(related_name='voters', to='polls.Student'),
        ),
    ]
