# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-03 19:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0013_question_question_voters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
