# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-03 19:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0015_auto_20160603_1531'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='question_voters',
        ),
    ]
