# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-22 16:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0020_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='image',
            field=models.CharField(default='https://pbs.twimg.com/media/B0eebrtIUAEVFad.jpg', max_length=500),
        ),
        migrations.AddField(
            model_name='question',
            name='question_desc',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='status',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=models.CharField(max_length=20),
        ),
    ]
