# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-28 22:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0023_question_display_pref'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='send_email',
            field=models.BooleanField(default=True),
        ),
    ]
