# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-29 02:23
from __future__ import unicode_literals

from django.db import migrations, models
import polls.models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0024_question_send_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=polls.models.get_image_path),
        ),
    ]
