# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-29 17:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0025_question_poll_algorithm'),
        ('polls', '0025_item_image'),
    ]

    operations = [
    ]
