# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-29 19:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0026_merge'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='winner',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/items/'),
        ),
    ]
