# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-02 21:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0027_auto_20160629_1552'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='send_email',
            new_name='emailInvite',
        ),
        migrations.AddField(
            model_name='question',
            name='emailDelete',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='question',
            name='emailStart',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='question',
            name='emailStop',
            field=models.BooleanField(default=True),
        ),
    ]
