# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-05 17:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0029_question_question_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='imageURL',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='imageURL',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/items/'),
        ),
    ]
