# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-05 19:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0032_auto_20160705_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/img/items/'),
        ),
    ]
