# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-05 20:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0034_auto_20160705_1604'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='image',
        ),
        migrations.AddField(
            model_name='question',
            name='imageFile',
            field=models.ImageField(blank=True, null=True, upload_to='static/img/items/'),
        ),
    ]
