# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-08 06:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0036_auto_20160705_1630'),
    ]

    operations = [
        migrations.CreateModel(
            name='OldWinner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Item')),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Response')),
            ],
        ),
    ]
