# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-08 06:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0038_oldwinner_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oldwinner',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Question'),
        ),
    ]
