# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-09 23:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0039_auto_20160708_0218'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oldwinner',
            name='item',
        ),
    ]
