# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-08 07:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0039_auto_20160708_0218'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='m_poll',
            field=models.BooleanField(default=False),
        ),
    ]
