# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-10 08:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polls', '0040_question_m_poll'),
    ]

    operations = [
        migrations.CreateModel(
            name='Combination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dependencies', models.ManyToManyField(to='polls.Item')),
                ('dependent_questions', models.ManyToManyField(related_name='dependent_questions', to='polls.Question')),
                ('response', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='polls.Response')),
                ('target_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
