# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-10 10:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0043_auto_20160710_1001'),
        ('polls', '0040_remove_oldwinner_item'),
    ]

    operations = [
    ]
