# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-10 21:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0044_merge'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='openHistory',
            field=models.BooleanField(default=False),
        ),
    ]
