# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-10 21:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0045_question_openhistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='openHistory',
        ),
    ]
