# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-18 14:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0046_remove_question_openhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_voters',
            field=models.ManyToManyField(related_name='poll_participated', to=settings.AUTH_USER_MODEL),
        ),
    ]
