# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-18 19:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0047_auto_20160717_1541'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConditionalItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='combination',
            name='dependencies',
        ),
        migrations.RemoveField(
            model_name='combination',
            name='response',
        ),
        migrations.AddField(
            model_name='conditionalitem',
            name='combination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Combination'),
        ),
        migrations.AddField(
            model_name='conditionalitem',
            name='items',
            field=models.ManyToManyField(to='polls.Item'),
        ),
        migrations.AddField(
            model_name='conditionalitem',
            name='response',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.Response'),
        ),
    ]
