# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-19 14:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0048_auto_20160718_1554'),
        ('polls', '0048_auto_20160719_1406'),
        ('polls', '0049_emailresponse_identity'),
    ]

    operations = [
    ]
