# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-19 14:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0050_merge'),
    ]

    operations = [
        migrations.AddField(
            model_name='combination',
            name='dependencies',
            field=models.ManyToManyField(to='polls.Item'),
        ),
        migrations.AddField(
            model_name='combination',
            name='response',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.Response'),
        ),
    ]
