# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-19 15:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0051_auto_20160719_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='comment',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
