# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-19 18:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0052_response_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anonymousvoter',
            name='question',
        ),
        migrations.AlterField(
            model_name='response',
            name='anonymous_voter',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='AnonymousVoter',
        ),
    ]
