# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-19 23:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0053_auto_20160719_1935'),
        ('polls', '0053_email'),
    ]

    operations = [
    ]
