# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-22 15:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0055_response_anonymous_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='anonymous_id',
            field=models.IntegerField(default=0),
        ),
    ]
