# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-25 14:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0056_auto_20160722_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
