# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-28 20:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0057_item_item_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='combination',
            name='dependencies',
        ),
        migrations.RemoveField(
            model_name='combination',
            name='dependent_questions',
        ),
        migrations.RemoveField(
            model_name='combination',
            name='response',
        ),
        migrations.RemoveField(
            model_name='combination',
            name='target_question',
        ),
        migrations.RemoveField(
            model_name='combination',
            name='user',
        ),
        migrations.RemoveField(
            model_name='conditionalitem',
            name='combination',
        ),
        migrations.RemoveField(
            model_name='conditionalitem',
            name='items',
        ),
        migrations.RemoveField(
            model_name='conditionalitem',
            name='response',
        ),
        migrations.DeleteModel(
            name='Combination',
        ),
        migrations.DeleteModel(
            name='ConditionalItem',
        ),
    ]
