# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-05 10:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0059_auto_20160805_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voteresult',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.Question'),
        ),
    ]
