# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-08 00:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0060_auto_20160805_1106'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='voteresult',
            options={'ordering': ['-timestamp']},
        ),
    ]
