# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-26 12:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0061_auto_20160807_2046'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='creator_pref',
            field=models.IntegerField(default=1),
        ),
    ]
