# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-12 20:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0062_question_creator_pref'),
    ]

    operations = [
        migrations.AddField(
            model_name='voteresult',
            name='cand_num',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='voteresult',
            name='mov_string',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='voteresult',
            name='result_string',
            field=models.CharField(default='', max_length=500),
        ),
    ]
