# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-04 03:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0063_auto_20160912_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='resp_str',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
