# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-04 05:00
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0064_response_resp_str'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['timestamp']},
        ),
        migrations.AddField(
            model_name='item',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2016, 10, 4, 5, 0, 18, 776428, tzinfo=utc), verbose_name='item timestamp'),
        ),
    ]
