# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-04 06:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0065_auto_20161004_0100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='timestamp',
            field=models.DateTimeField(verbose_name='item timestamp'),
        ),
    ]
