# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-26 03:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0069_auto_20161025_2323'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='response',
            options={'ordering': ['timestamp']},
        ),
    ]
