# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-13 22:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0070_auto_20161025_2325'),
    ]

    operations = [
        migrations.AddField(
            model_name='uservoterecord',
            name='initial_order',
            field=models.CharField(default='', max_length=400),
        ),
        migrations.AlterField(
            model_name='uservoterecord',
            name='record',
            field=models.CharField(max_length=1000),
        ),
    ]
