# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-29 14:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0072_uservoterecord_device'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uservoterecord',
            name='user',
            field=models.CharField(default='(Anonymous)', max_length=100),
        ),
    ]
