# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-30 20:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0073_auto_20161129_0938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='open',
            field=models.IntegerField(default=0),
        ),
    ]
