# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-31 19:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0074_auto_20161130_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='active',
            field=models.IntegerField(default=1),
        ),
    ]
