# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-16 05:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0075_response_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_string', models.CharField(default='', max_length=500)),
                ('mov_string', models.CharField(default='', max_length=200)),
                ('cand_num', models.IntegerField(default=1)),
                ('timestamp', models.DateTimeField(verbose_name='result timestamp')),
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='polls.Question')),
            ],
        ),
        migrations.AddField(
            model_name='uservoterecord',
            name='final_order',
            field=models.CharField(default='', max_length=400),
        ),
    ]
