# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-27 05:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0078_auto_20170127_0054'),
    ]

    operations = [
        migrations.AddField(
            model_name='finalresult',
            name='shade_string',
            field=models.CharField(default='', max_length=600),
        ),
    ]
