# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-16 05:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0079_finalresult_shade_string'),
    ]

    operations = [
        migrations.AddField(
            model_name='uservoterecord',
            name='comment_time',
            field=models.CharField(default='', max_length=100),
        ),
    ]
