# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-06 21:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0081_auto_20170306_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finalresult',
            name='edge_string',
            field=models.CharField(default='', max_length=10000),
        ),
        migrations.AlterField(
            model_name='finalresult',
            name='mov_string',
            field=models.CharField(default='', max_length=10000),
        ),
        migrations.AlterField(
            model_name='finalresult',
            name='node_string',
            field=models.CharField(default='', max_length=10000),
        ),
        migrations.AlterField(
            model_name='finalresult',
            name='result_string',
            field=models.CharField(default='', max_length=10000),
        ),
        migrations.AlterField(
            model_name='finalresult',
            name='shade_string',
            field=models.CharField(default='', max_length=10000),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='response',
            name='resp_str',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='uservoterecord',
            name='record',
            field=models.CharField(max_length=10000),
        ),
    ]
