# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-23 19:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0082_auto_20170306_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='new_vote',
            field=models.BooleanField(default=False),
        ),
    ]
