# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-29 08:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0083_question_new_vote'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='recently_added',
            field=models.BooleanField(default=False),
        ),
    ]
