# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-30 07:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0084_item_recently_added'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(default='', max_length=10000)),
                ('timestamp', models.DateTimeField(verbose_name='message timestamp')),
            ],
        ),
    ]
