# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-04 14:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0086_message_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='winner',
            field=models.CharField(default='', max_length=200),
        ),
    ]
