# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-04-20 13:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0088_auto_20170404_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='mixtures_pl',
            field=models.CharField(default='', max_length=500),
        ),
    ]
