# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-04-22 00:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0089_question_mixtures_pl'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='mixtures_pl',
            new_name='mixtures_pl1',
        ),
        migrations.AddField(
            model_name='question',
            name='mixtures_pl2',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='question',
            name='mixtures_pl3',
            field=models.CharField(default='', max_length=500),
        ),
    ]
