# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-30 01:07
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0090_auto_20170421_2036'),
    ]

    operations = [
        migrations.AddField(
            model_name='uservoterecord',
            name='slider',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='uservoterecord',
            name='star',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
