# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-30 01:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0090_auto_20170421_2036'),
    ]

    operations = [
        migrations.AddField(
            model_name='uservoterecord',
            name='slider',
            field=models.CharField(max_length=200,default=''),
        ),
        migrations.AddField(
            model_name='uservoterecord',
            name='star',
            field=models.CharField(max_length=200,default=''),
        ),
    ]
