# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-30 01:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0091_auto_20170529_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uservoterecord',
            name='slider',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='uservoterecord',
            name='star',
            field=models.TextField(default=''),
        ),
    ]
