# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-30 01:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0092_auto_20170529_2127'),
    ]

    operations = [
        migrations.AddField(
            model_name='uservoterecord',
            name='swit',
            field=models.TextField(default=''),
        ),
    ]
