# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-01 18:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0094_auto_20170601_0031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finalresult',
            name='edge_string',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='finalresult',
            name='mov_string',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='finalresult',
            name='node_string',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='finalresult',
            name='result_string',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='finalresult',
            name='shade_string',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='voteresult',
            name='mov_string',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='voteresult',
            name='result_string',
            field=models.TextField(default=''),
        ),
    ]
