# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-06 00:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0095_auto_20170601_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='initial_ui',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='question',
            name='onecol_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='question',
            name='slider_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='question',
            name='star_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='question',
            name='twocol_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
