# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-08 05:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0096_auto_20170605_2034'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='yesno_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
