# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-09 07:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0097_question_yesno_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='ui_number',
            field=models.IntegerField(default=5),
        ),
    ]
