# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-06-16 02:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0098_question_ui_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='vote_rule',
            field=models.IntegerField(default=4095),
        ),
    ]
