# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-19 17:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0102_auto_20170703_2115'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='first',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='question',
            name='next',
            field=models.IntegerField(default=-1),
        ),
    ]
