# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-17 15:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0103_auto_20171019_1251'),
    ]

    operations = [
        migrations.AddField(
            model_name='uservoterecord',
            name='one_col',
            field=models.TextField(default=''),
        ),
    ]
