# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-25 04:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0104_uservoterecord_one_col'),
    ]

    operations = [
        migrations.AddField(
            model_name='uservoterecord',
            name='submit_time',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='uservoterecord',
            name='ui',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='uservoterecord',
            name='final_order',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='uservoterecord',
            name='initial_order',
            field=models.TextField(default=''),
        ),
    ]
