# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-01 17:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0105_auto_20171224_2353'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='yesno2_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
