# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-02 02:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0106_question_yesno2_enabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='ui_number',
            field=models.IntegerField(default=6),
        ),
        migrations.AlterField(
            model_name='question',
            name='yesno2_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
