# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-06 00:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0107_auto_20180101_2108'),
        ('polls', '0107_auto_20180105_1858'),
    ]

    operations = [
    ]
