# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-01 23:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0107_auto_20180101_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='yesno2_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
