# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-02 02:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0107_auto_20180101_2108'),
        ('polls', '0108_auto_20180101_1820'),
    ]

    operations = [
    ]
