# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-18 18:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0108_merge_20180105_1930'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='behavior_data',
            field=models.TextField(default=''),
        ),
    ]
