# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-06 00:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0109_merge_20180101_2112'),
        ('polls', '0108_merge_20180105_1930'),
    ]

    operations = [
    ]
