# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-19 00:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0109_response_behavior_data'),
        ('polls', '0110_merge_20180105_1946'),
    ]

    operations = [
    ]
