# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-12 02:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0112_experiment'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='first_tier',
            field=models.IntegerField(default=0),
        ),
    ]
