# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-07 01:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0113_question_first_tier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='mixtures_pl1',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='question',
            name='mixtures_pl2',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='question',
            name='mixtures_pl3',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_desc',
            field=models.TextField(blank=True, null=True),
        ),
    ]
