# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-05-13 21:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0115_auto_20180511_1054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='utility_model_enabled',
        ),
        migrations.AddField(
            model_name='question',
            name='utility_model',
            field=models.IntegerField(default=0),
        ),
    ]
