# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-05-15 13:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0116_auto_20180513_1607'),
    ]

    operations = [
        migrations.CreateModel(
            name='RandomUtilityPool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.TextField(default='[]')),
            ],
        ),
    ]
