# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-07-10 13:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0118_auto_20180709_0124'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='single_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
