# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-07-11 13:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0119_question_single_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='correct_answer',
            field=models.TextField(default=''),
        ),
    ]
