# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-07-31 13:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polls', '0122_question_single_enabled'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignUpRequests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.TextField()),
                ('status', models.IntegerField(default=1)),
                ('timestamp', models.DateTimeField(verbose_name='request timestamp')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='self_sign_up_user_id',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='question',
            name='allow_self_sign_up',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='signuprequests',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Question'),
        ),
        migrations.AddField(
            model_name='signuprequests',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
