# Generated by Django 2.2 on 2019-05-07 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0124_auto_20180731_0859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='response',
            name='resp_str',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
