# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-18 14:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multipolls', '0002_multipoll_pos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multipoll',
            name='voters',
            field=models.ManyToManyField(related_name='multipoll_participated', to=settings.AUTH_USER_MODEL),
        ),
    ]
