# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-19 14:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('multipolls', '0003_auto_20160718_1028'),
        ('multipolls', '0003_auto_20160717_1541'),
    ]

    operations = [
    ]
