# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-11 23:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multipolls', '0006_auto_20160728_1959'),
    ]

    operations = [
        migrations.AddField(
            model_name='multipoll',
            name='emailDelete',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='multipoll',
            name='emailInvite',
            field=models.BooleanField(default=True),
        ),
    ]
